In [26]:
import pandas as pd
import numpy as np
from math import sqrt

In [2]:
df = pd.read_csv("./dataset/diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [49]:
# Glucode BloodPressure BMI Age
# row1 = np.array([148, 72, 33.6, 50])
row1 = np.array([148, 72])
# row2 = np.array([85, 66, 26.6, 31])
row2 = np.array([85, 66])
# row3 = np.array([183, 64, 23.3, 32])
row3 = np.array([183, 64])
# row4 = np.array([89, 66, 28.1, 21])
row4 = np.array([89, 66])
# row5 = np.array([137, 40, 43.1, 33])
row5 = np.array([137, 40])
rows = np.array([row1, row2, row3, row4, row5, [110, 55]])

for i in range(len(rows)):
    print(f"for {rows[i]}, class { 1 if i % 2 == 0 else 0 }")
    for j in range(len(rows)):
        if i == j:
            print(0)
            continue
        print((sum(abs((np.array(rows[i]) - np.array(rows[j])))**2)**(1/2)),  f"class { 1 if j % 2 == 0 else 0 }")
    print()
        # print(np.linalg.norm(np.array(rows[i]) - np.array(rows[j])), f"class { 1 if j % 2 == 0 else 0 }")

for [148  72], class 1
0
63.28506932918696 class 0
35.90264614203248 class 1
59.30430001273095 class 0
33.83784863137726 class 1
41.6293165929973 class 0

for [85 66], class 0
63.28506932918696 class 1
0
98.02040603874276 class 1
4.0 class 0
58.137767414994535 class 1
27.313000567495326 class 0

for [183  64], class 1
35.90264614203248 class 1
98.02040603874276 class 0
0
94.02127418834527 class 0
51.884487084291386 class 1
73.55270219373317 class 0

for [89 66], class 0
59.30430001273095 class 1
4.0 class 0
94.02127418834527 class 1
0
54.589376255824725 class 1
23.706539182259394 class 0

for [137  40], class 1
33.83784863137726 class 1
58.137767414994535 class 0
51.884487084291386 class 1
54.589376255824725 class 0
0
30.886890422961002 class 0

for [110  55], class 0
41.6293165929973 class 1
27.313000567495326 class 0
73.55270219373317 class 1
23.706539182259394 class 0
30.886890422961002 class 1
0

In [14]:
count_out = 0
count_in = 0
sum_row = 0

for index, rows in df.iterrows():
    if count_out == 5:
        count_out = 0
        break

    print(f"outcome out: { rows.Outcome }")

    sum_row = np.array(rows)

    for ind, row in df.iterrows():
        if ind == index:
            continue
        if count_in == 5:
            count_in = 0
            break

        print(f"outcome in: { row.Outcome }")

        print(np.linalg.norm(np.array(rows) - np.array(row)))
        count_in += 1

    count_out += 1
    print()
    # print(np.array(rows))

outcome out: 1.0
outcome in: 0.0
66.91095706982526
outcome in: 1.0
54.29633528149022
outcome in: 0.0
115.73444431110386
outcome in: 1.0
172.5891332645251
outcome in: 0.0
52.145771410537215

outcome out: 0.0
outcome in: 1.0
66.91095706982526
outcome in: 1.0
102.52313417468274
outcome in: 0.0
94.81710740156547
outcome in: 1.0
178.66729406637356
outcome in: 0.0
43.40532801396621

outcome out: 1.0
outcome in: 1.0
54.29633528149022
outcome in: 0.0
102.52313417468274
outcome in: 0.0
135.64400106528853
outcome in: 1.0
180.55650488420517
outcome in: 0.0
67.88602095424359

outcome out: 0.0
outcome in: 1.0
115.73444431110386
outcome in: 0.0
94.81710740156547
outcome in: 1.0
135.64400106528853
outcome in: 1.0
94.73910829747132
outcome in: 0.0
101.29783391563711

outcome out: 1.0
outcome in: 1.0
172.5891332645251
outcome in: 0.0
178.66729406637356
outcome in: 1.0
180.55650488420517
outcome in: 0.0
94.73910829747132
outcome in: 0.0
177.17676362604664